theme: jekyll-theme-minimal
title: Miami Valley Traffic Net
show_downloads: false
description: Serving Dayton, OH and Surrounding Areas<br><br>Participating in the ARRL National Traffic System</br>
logo: http://www.arrl.org/images/view/Public_Service/nts_cl.gif
author: KC8ZUB
